export enum ROLE {
  ADMIN = 'ADMIN',
  CONSUMER = 'CONSUMER',
  MANAGER = 'MANAGER',
  PRODUCER = 'PRODUCER',
  RETAILER = 'RETAILER',
  PROCESSOR = 'PROCESSOR',
  TRANSPORTER = 'TRANSPORTER',
  AUDITOR = 'AUDITOR',
}
